services:
  backend-dev:
    build:
      context: ./students-city-api
      dockerfile: Dockerfile
    container_name: studentscity-backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./students-city-api:/app:delegated
    env_file:
      - ./students-city-api/.env
      - ./students-city-api/.env.local
    networks:
      - plane-net
      - db-net
      - studentscity-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=plane-app_default"
      - "traefik.http.routers.studentscity-api.rule=Host(`studentscity.dev.cloudforgestudio.fr`)"
      - "traefik.http.routers.studentscity-api.entrypoints=websecure"
      - "traefik.http.routers.studentscity-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.studentscity-api.loadbalancer.server.port=8000"

networks:
  db-net:
    external: true
    name: infra-databases_db-net
  plane-net:
    external: true
    name: plane-app_default
  studentscity-net:
    driver: bridge