lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    clock_skew: 0
    allow_no_expiration: false
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
