name: Backend CI / CD Pipeline

permissions:
  contents: write

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  backend-lint-test:
    name: Lint & Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, xml, intl

      - name: Install Composer dependencies
        working-directory: ./students-city-api
        run: composer install --prefer-dist --no-progress --no-interaction

  backend-deploy-dev:
    name: Deploy to STAGING (Docker)
    needs: backend-lint-test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH & deploy via Docker Compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:      ${{ secrets.SERVER_HOST }}
          username:  ${{ secrets.SERVER_USER }}
          key:       ${{ secrets.SERVER_SSH_KEY }}
          port:      ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "🔄 Déploiement Symfony en staging via Docker..."

            cd /opt/projects/studentscity/code/dev

            git reset --hard
            git clean -fd
            git fetch --all
            git checkout dev
            git pull origin dev

            cat > students-city-api/.env.local << 'EOF'
            APP_ENV=dev
            APP_SECRET=${{ secrets.APP_SECRET }}
            DATABASE_URL="mysql://students-city_user:dev:${{ secrets.DB_DEV_PASSWORD }}@mysql-db:3306/students_city?serverVersion=8.0&charset=utf8mb4"
            JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
            JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
            JWT_PASSPHRASE=${{ secrets.JWT_PASSPHRASE }}
            EOF

            docker compose -f docker-compose.dev.yml pull backend-dev
            docker compose -f docker-compose.dev.yml up -d --build backend-dev
            docker compose -f docker-compose.dev.yml ps